GET http://localhost:3000/api/Usuario

###

POST http://localhost:3000/api/Usuario
Content-Type: application/json

{
    "nome": "pedro",
    "email": "p@p.com",
    "senha": "zzz",
    "saldo": 00.00
}
 
 ###


PATCH  http://localhost:3000/api/Usuario/1
Content-Type: application/json

{
    "nome": "Pedro Pais"
}


###


DELETE http://localhost:3000/api/Usuario/1